In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [3]:
#create dataset
features = torch.randn((10, 5))

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.5967],
        [0.2002],
        [0.7590],
        [0.5798],
        [0.6908],
        [0.3195],
        [0.7474],
        [0.8126],
        [0.2879],
        [0.8753]], grad_fn=<SigmoidBackward0>)

In [4]:
#show model weights 
model.linear.weight

Parameter containing:
tensor([[ 0.3303, -0.4351,  0.4283, -0.2316,  0.3652]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.3345], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 4),
            nn.ReLU(),
            nn.Linear(4, 1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        return out

In [16]:
#create dataset
features = torch.randn((10, 5))

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4444],
        [0.5171],
        [0.6245],
        [0.5964],
        [0.5744],
        [0.5444],
        [0.5266],
        [0.5355],
        [0.5752],
        [0.6175]], grad_fn=<SigmoidBackward0>)

In [20]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 4]                   24
│    └─ReLU: 2-2                         [10, 4]                   --
│    └─Linear: 2-3                       [10, 1]                   5
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 29
Trainable params: 29
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00