In [1]:
import numpy as np
import pandas as pd 
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv(r"C:\Users\Piyush Singh\breast_cancer.csv")


In [4]:
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [7]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [8]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train Test Split 

In [17]:
x_train , x_test , y_train , y_test = train_test_split(df.iloc[: ,1 :],df.iloc[:,0],test_size=0.2,random_state=42  )

Scaling

In [18]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [19]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [20]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding 


In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [22]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

Numpy Arrays To Pytorch Tensors 

In [23]:
x_train_tensor = torch.tensor(x_train)
x_test_tensor = torch.tensor(x_test)

y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [24]:
x_train_tensor.shape , y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

In [25]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

Defining The Model

In [31]:
class MySimpleNN():
    def __init__(self , x):
        self.weight = torch.randn(x.shape[1],1 ,dtype= torch.float64 , requires_grad=True)
        self.bias = torch.randn(1, dtype= torch.float64 , requires_grad=True)
        
    def forward(self , x):
        return torch.sigmoid(torch.matmul(x , self.weight) + self.bias) 
    
    def loss_function(self , y_pred , y):
        #clamp predicted values to avoid log(0) error
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred , epsilon , 1. - epsilon)
        
        #calculate loss 
        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss 
        

In [30]:
learning_rate = 0.01
epochs  = 25

In [34]:
#training pipeline
model = MySimpleNN(x_train_tensor)
model.weight

#forward pass
for epoch in range(epochs):
    y_pred = model.forward(x_train_tensor)
    
    # #reshaping y_train_tensor
    # y_train_tensor_reshaped = y_train_tensor.view(-1,1).type(torch.float64)
    
    #loss calculation
    loss = model.loss_function(y_pred , y_train_tensor)
    
    #backward pass
    loss.backward()
    
    #updating weights and bias
    with torch.no_grad():
        model.weight -= learning_rate * model.weight.grad
        model.bias -= learning_rate * model.bias.grad
        
        #zeroing the gradients
    model.weight.grad.zero_()
    model.bias.grad.zero_()
        
  
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")




Epoch 1/25, Loss: 1.5560
Epoch 2/25, Loss: 1.5515
Epoch 3/25, Loss: 1.5470
Epoch 4/25, Loss: 1.5425
Epoch 5/25, Loss: 1.5381
Epoch 6/25, Loss: 1.5336
Epoch 7/25, Loss: 1.5292
Epoch 8/25, Loss: 1.5248
Epoch 9/25, Loss: 1.5204
Epoch 10/25, Loss: 1.5160
Epoch 11/25, Loss: 1.5117
Epoch 12/25, Loss: 1.5074
Epoch 13/25, Loss: 1.5031
Epoch 14/25, Loss: 1.4988
Epoch 15/25, Loss: 1.4945
Epoch 16/25, Loss: 1.4903
Epoch 17/25, Loss: 1.4860
Epoch 18/25, Loss: 1.4818
Epoch 19/25, Loss: 1.4776
Epoch 20/25, Loss: 1.4734
Epoch 21/25, Loss: 1.4693
Epoch 22/25, Loss: 1.4651
Epoch 23/25, Loss: 1.4610
Epoch 24/25, Loss: 1.4569
Epoch 25/25, Loss: 1.4528


In [35]:
model.weight

tensor([[-0.3462],
        [-0.7853],
        [-0.1181],
        [ 0.3965],
        [-0.3123],
        [-0.1363],
        [ 0.5249],
        [ 0.1766],
        [-0.2685],
        [-0.0180],
        [-1.0644],
        [ 1.0176],
        [-0.4660],
        [-0.0883],
        [-0.9541],
        [-1.3749],
        [ 0.7433],
        [ 1.2377],
        [ 0.0063],
        [ 1.4874],
        [ 0.5220],
        [-0.2660],
        [ 0.2772],
        [-1.7172],
        [ 0.4760],
        [ 2.0450],
        [-0.9449],
        [-0.5437],
        [ 0.1308],
        [ 1.2753]], dtype=torch.float64, requires_grad=True)

In [36]:
model.bias

tensor([-0.8862], dtype=torch.float64, requires_grad=True)

In [37]:
#evaluation
with torch.no_grad():
    y_test_pred = model.forward(x_test_tensor)
    y_test_pred_class = y_test_pred.round()
    
    accuracy = (y_test_pred_class.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item():.4f}")

Test Accuracy: 0.5702
