In [3]:
!pip install torch torchvision torchaudio


  Using cached torchvision-0.23.0-cp310-cp310-win_amd64.whl.metadata (6.1 kB)
  Using cached torch-2.8.0-cp310-cp310-win_amd64.whl.metadata (30 kB)
Using cached torchvision-0.23.0-cp310-cp310-win_amd64.whl (1.6 MB)
Using cached torch-2.8.0-cp310-cp310-win_amd64.whl (241.4 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 28.7 MB/s eta 0:00:00

  Attempting uninstall: torch

    Found existing installation: torch 2.7.1

   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [to

In [4]:
import torch
import torchvision

In [5]:
a = torch.empty(2,3)

In [6]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
b = torch.zeros(2,3)

In [8]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
c = torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand 
torch.rand(2,3)

tensor([[0.5558, 0.5735, 0.6243],
        [0.1680, 0.5929, 0.2265]])

In [13]:
#use of seed 
torch.manual_seed(100)
torch.rand(2,3)
# same code koi aur run karega if seed same hoga to output bhi same hoga

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
#using tensor
torch.tensor([[5,9,3],[4,5,6]])

tensor([[5, 9, 3],
        [4, 5, 6]])

In [17]:
#other ways
#arange 
print("using arange ->" , torch.arange(1,10,2))
      
#using linspace
print("using linspace ->", torch.linspace(1,10,5))

#using eye
print("using eye ->", torch.eye(3,3))

#using full 
print("using full ->", torch.full((2,3),7))


using arange -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[7, 7, 7],
        [7, 7, 7]])


**TENSORS SHAPES**

In [18]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [33]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

**TENSOR DATA TYPE**

In [25]:
x.dtype

torch.int64

In [27]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [34]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [35]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [36]:
x*3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [37]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [38]:
(x*100)/3

tensor([[ 33.3333,  66.6667, 100.0000],
        [133.3333, 166.6667, 200.0000]])

Element Wise Operation

In [39]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [41]:
print(a)
print(b)


tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [42]:
a+b

tensor([[0.9717, 1.1950, 1.5354],
        [0.9127, 0.2595, 0.9212]])

In [43]:
a-b

tensor([[-0.0837,  0.7007, -0.0464],
        [ 0.0657,  0.2257,  0.4794]])

In [44]:
a*b

tensor([[0.2343, 0.2343, 0.5888],
        [0.2072, 0.0041, 0.1547]])

In [45]:
a/b

tensor([[ 0.8415,  3.8346,  0.9413],
        [ 1.1552, 14.3533,  3.1705]])

In [46]:
a**b

tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])

In [47]:
a%b

tensor([[0.4440, 0.2063, 0.7445],
        [0.0657, 0.0060, 0.0377]])

In [48]:
c =torch.tensor([1 , -2 , 3 , -4   ])

In [49]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [50]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [51]:
d = torch.tensor([1.9 , -2.5 , 3.1 , -4.6   ])

In [52]:
torch.round(d)

tensor([ 2., -2.,  3., -5.])

In [53]:
torch.ceil(d)

tensor([ 2., -2.,  4., -4.])

In [55]:
#matrix operations
f = torch.randint(size =(2,3), low=1 , high=10)
g = torch.randint(size =(3,2), low=1 , high=10)

In [56]:
print(f)
print(g)

tensor([[7, 4, 9],
        [3, 7, 6]])
tensor([[7, 4],
        [1, 7],
        [5, 4]])


In [57]:
#matrix multiplication 
torch.matmul(f,g)

tensor([[98, 92],
        [58, 85]])

In [58]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [59]:
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [60]:
#transpose
torch.t(f)

tensor([[7, 3],
        [4, 7],
        [9, 6]])

In [61]:
h = torch.randint(size =(2,3), low=1 , high=10 , dtype=torch.float32 )
h

tensor([[7., 2., 1.],
        [1., 4., 6.]])

In [62]:
#determinant
torch.det(torch.matmul(h,torch.t(h)))

tensor(2421.)

In [63]:
#inverse
torch.inverse(torch.matmul(h,torch.t(h)))

tensor([[ 0.0219, -0.0087],
        [-0.0087,  0.0223]])

**Comparision Operations**

In [64]:
i = torch.randint(size =(2,3), low=1 , high=10)
j = torch.randint(size =(2,3), low=1 , high=10)

In [65]:
print(i)
print(j)

tensor([[6, 6, 1],
        [4, 1, 3]])
tensor([[7, 2, 2],
        [8, 4, 1]])


In [67]:
#greater than 
i>j


#less than 
i<j

#equal to
i==j
#not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [68]:
torch.log(i)

tensor([[1.7918, 1.7918, 0.0000],
        [1.3863, 0.0000, 1.0986]])

In [69]:
torch.sqrt(i)

tensor([[2.4495, 2.4495, 1.0000],
        [2.0000, 1.0000, 1.7321]])

In [70]:
torch.sigmoid(i)

tensor([[0.9975, 0.9975, 0.7311],
        [0.9820, 0.7311, 0.9526]])

In [71]:
torch.relu(i)

tensor([[6, 6, 1],
        [4, 1, 3]])

In [72]:
l = i.clone()

In [73]:
l

tensor([[6, 6, 1],
        [4, 1, 3]])

In [74]:
i

tensor([[6, 6, 1],
        [4, 1, 3]])

In [75]:
i[0][0] = 16

In [76]:
i

tensor([[16,  6,  1],
        [ 4,  1,  3]])

In [77]:
l

tensor([[6, 6, 1],
        [4, 1, 3]])

In [78]:
torch.cuda.is_available()

False

In [79]:
p = torch.ones(4,4)

In [80]:
p

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
p.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [83]:
p.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
b = torch.rand(2,3,4)
b

tensor([[[0.7775, 0.6179, 0.3379, 0.2170],
         [0.9454, 0.7116, 0.1157, 0.6574],
         [0.3451, 0.0453, 0.9798, 0.5548]],

        [[0.6868, 0.4920, 0.0748, 0.9605],
         [0.3271, 0.0103, 0.9516, 0.2855],
         [0.2324, 0.9141, 0.7668, 0.1659]]])

In [85]:
b.permute(2,0,1)

tensor([[[0.7775, 0.9454, 0.3451],
         [0.6868, 0.3271, 0.2324]],

        [[0.6179, 0.7116, 0.0453],
         [0.4920, 0.0103, 0.9141]],

        [[0.3379, 0.1157, 0.9798],
         [0.0748, 0.9516, 0.7668]],

        [[0.2170, 0.6574, 0.5548],
         [0.9605, 0.2855, 0.1659]]])

In [86]:
#unsqueeze
c = torch.rand(226,226,3)

In [87]:
c

tensor([[[4.3933e-01, 2.2428e-01, 8.9348e-01],
         [4.9744e-02, 1.7798e-01, 3.0110e-01],
         [1.8930e-01, 9.1860e-01, 2.1314e-01],
         ...,
         [8.2998e-02, 4.4943e-01, 1.5051e-01],
         [7.6906e-01, 8.7778e-01, 4.8540e-02],
         [3.3420e-01, 8.5171e-01, 4.7959e-01]],

        [[3.2434e-01, 1.8597e-01, 3.4846e-01],
         [7.8238e-01, 5.8968e-01, 3.0883e-01],
         [3.3913e-01, 2.7369e-01, 2.1418e-01],
         ...,
         [1.7131e-02, 7.0495e-01, 4.7828e-01],
         [2.9134e-01, 6.0935e-01, 6.4412e-01],
         [4.8498e-01, 5.3358e-01, 7.2390e-01]],

        [[3.0787e-01, 9.1050e-01, 7.6694e-01],
         [9.8230e-01, 7.7509e-01, 6.9012e-01],
         [3.7143e-01, 1.6246e-01, 5.4050e-01],
         ...,
         [6.1446e-01, 4.6134e-01, 5.8670e-02],
         [8.9711e-01, 7.0354e-01, 4.2692e-01],
         [6.8473e-01, 1.4796e-01, 9.4666e-01]],

        ...,

        [[7.9036e-04, 7.6589e-01, 1.1013e-01],
         [4.9911e-01, 2.1377e-01, 7.5163e-01]

In [89]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [91]:
#squeeze
c.squeeze()

tensor([[[4.3933e-01, 2.2428e-01, 8.9348e-01],
         [4.9744e-02, 1.7798e-01, 3.0110e-01],
         [1.8930e-01, 9.1860e-01, 2.1314e-01],
         ...,
         [8.2998e-02, 4.4943e-01, 1.5051e-01],
         [7.6906e-01, 8.7778e-01, 4.8540e-02],
         [3.3420e-01, 8.5171e-01, 4.7959e-01]],

        [[3.2434e-01, 1.8597e-01, 3.4846e-01],
         [7.8238e-01, 5.8968e-01, 3.0883e-01],
         [3.3913e-01, 2.7369e-01, 2.1418e-01],
         ...,
         [1.7131e-02, 7.0495e-01, 4.7828e-01],
         [2.9134e-01, 6.0935e-01, 6.4412e-01],
         [4.8498e-01, 5.3358e-01, 7.2390e-01]],

        [[3.0787e-01, 9.1050e-01, 7.6694e-01],
         [9.8230e-01, 7.7509e-01, 6.9012e-01],
         [3.7143e-01, 1.6246e-01, 5.4050e-01],
         ...,
         [6.1446e-01, 4.6134e-01, 5.8670e-02],
         [8.9711e-01, 7.0354e-01, 4.2692e-01],
         [6.8473e-01, 1.4796e-01, 9.4666e-01]],

        ...,

        [[7.9036e-04, 7.6589e-01, 1.1013e-01],
         [4.9911e-01, 2.1377e-01, 7.5163e-01]

In [2]:
import torch

In [16]:
#autograd in pytorch 
x = torch.tensor(3.0 , requires_grad=True)

In [17]:
y =x**2

In [18]:
z = torch.sin(y)

In [19]:
x

tensor(3., requires_grad=True)

In [20]:
y

tensor(9., grad_fn=<PowBackward0>)

In [21]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [22]:
torch.autograd.grad(z , x)

(tensor(-5.4668),)

In [23]:
x = torch.tensor(6.7) #input feature
y = torch.tensor(0.0) #true label(binary)

w = torch.tensor(1.0) #weight
b = torch.tensor(0.0) #bias

In [24]:
#binary cross entropy loss for scalar
def binary_cross_entropy_loss(prediction , target):
    epsilon = 1e-8 #to avoid log(0)
    prediction = torch.clamp(prediction , epsilon , 1.0 - epsilon)
    return  -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))


In [25]:
#forward pass
z = w * x + b  #linear transformation
y_pred = torch.sigmoid(z)  #activation function

#compute binary cross entropy loss
loss = binary_cross_entropy_loss(y_pred , y)


In [26]:
loss

tensor(6.7012)

In [27]:
#derivatives 
#1. dl/d(y_pred) : loss wrt y_pred
dloss_dy_pred = (y_pred -y)/(y_pred * (1 - y_pred))

#2. d(y_pred)/dz : y_pred wrt z(sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

#3. dz/dw : z wrt w
dz_dw = x
#4 dz/db : z wrt b
dz_db = 1

dl_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dl_db = dloss_dy_pred * dy_pred_dz * dz_db
dl_dw , dl_db

(tensor(6.6918), tensor(0.9988))

In [28]:
print(f"Mannual Gradients of loss w.r.t weight (dw) : {dl_dw}")
print(f"Mannual Gradients of loss w.r.t bias (db) : {dl_db}")

Mannual Gradients of loss w.r.t weight (dw) : 6.691762447357178
Mannual Gradients of loss w.r.t bias (db) : 0.998770534992218


In [29]:
x = torch.tensor(3.0 , requires_grad=True)
x

tensor(3., requires_grad=True)

In [30]:
with torch.no_grad():
    y = x**2
y

tensor(9.)